In [1]:
import pandas as pd
import numpy as np

import statsmodels.api as sm
from statsmodels.formula.api import ols

from sklearn.model_selection import train_test_split , cross_val_score
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
linreg = LinearRegression()
from matplotlib import pyplot as plt

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
df = pd.read_csv('kc_house_data.csv')

In [4]:
df = df[['price', 'sqft_living', 'sqft_living15']]

In [5]:
target = 'price'
y = df[target]
X = df.drop(target, axis=1)

In [6]:
linreg.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [7]:
y_hats = linreg.predict(X)
y_hats[:5]

array([278014.31282749, 638830.49627888, 272524.81709126, 468482.0127479 ,
       430540.76040012])

In [8]:
errs = y - y_hats

In [9]:
# list(zip(errs, errs.abs()))[:5]

In [10]:
from sklearn.model_selection import KFold

In [11]:
# list(KFold(n_splits=5).split(X))

In [12]:
total_errs = np.array([])
k_vals = [5,10, 20]
for k in k_vals:
    for train_index, test_index in KFold(n_splits=k).split(X):

            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train, y_test = y.iloc[train_index], y.iloc[test_index]

            linreg.fit(X_train, y_train)
            y_hat = linreg.predict(X_test)
            errs = y_test - y_hat
            if True:
                errs = np.exp(y_test / y_hat)
            print(np.mean(errs))
            total_errs = np.concatenate((total_errs, errs))

3.1934993671764955
3.1746421454638636
3.1631003252929863
3.181043576223185
3.267966844643547
3.1567060561810654
3.258184291063082
3.160939463358958
3.211989583000116
3.1632462910205543
3.145649683352229
3.232421767538016
3.1179765460301123
3.339173782597157
3.128395150992486
3.1339258272200436
3.1943210965920916
3.1758653351309847
3.3459787633418796
3.167229832360761
3.1480793288519076
3.199009375240041
3.2699817057493403
3.1940106549418767
3.127146100673608
3.1418679622577113
3.1408369633917697
3.223738060413202
3.228485872703924
3.1484300299717094
3.0896623168375323
3.3753520174707665
3.2917741114684462
3.1751531553284096
3.0520582540035317


In [13]:
len(total_errs)

64791

In [14]:
model = ols(formula = 'price~sqft_living+sqft_living15', data = df).fit()

In [15]:
model.params

Intercept       -99260.708418
sqft_living        242.444418
sqft_living15       68.052693
dtype: float64

In [16]:
linreg.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [17]:
type(linreg.intercept_)

numpy.float64

In [18]:
linreg.coef_.shape

(2,)

In [19]:
np.array(model.params)

array([-9.92607084e+04,  2.42444418e+02,  6.80526925e+01])

In [20]:
# line = np.array(model.params)

In [21]:
from feat_to_model_eval import feat_to_model_kfold_eval, predict

In [22]:
feat_to_model_kfold_eval('price', df=df, kvals=[5,10,20], MAE=True)
print('hello')

Line: [-9.92607084e+04  2.42444418e+02  6.80526925e+01]
RMSE: 260417.4684450089
MAE: 173158.42264116395
THIS IS A STRINGGG
hello


In [25]:
line, rmse, mae = feat_to_model_kfold_eval('price', df=df, kvals=[5,10,20], show_summary=True, MAE=True)

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  price   R-squared:                       0.500
Model:                            OLS   Adj. R-squared:                  0.500
Method:                 Least Squares   F-statistic:                 1.078e+04
Date:                Wed, 17 Apr 2019   Prob (F-statistic):               0.00
Time:                        15:39:21   Log-Likelihood:            -2.9991e+05
No. Observations:               21597   AIC:                         5.998e+05
Df Residuals:                   21594   BIC:                         5.999e+05
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept     -9.926e+04   5427.190    -18.290      0.000    -1.1e+05   -8.86e+04
sqft_living     242.4444      2.945     82.329      0.000     236.672     248.216
sqft_living15    68.0527      3.946     17.248      0.000      60.319      75.786
==============================================================================
Omnibus:                    15568.864   Durbin-Watson:                   1.983
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           682653.257
Skew:                           2.983   Prob(JB):                         0.00
Kurtosis:                      29.889   Cond. No.                     9.42e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.42e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

Line: [-9.92607084e+04  2.42444418e+02  6.80526925e+01]
RMSE: 260417.4684450089
MAE: 173158.42264116395
THIS IS A STRINGGG


In [26]:
line

array([-9.92607084e+04,  2.42444418e+02,  6.80526925e+01])

In [27]:
rmse

260417.4684450089

In [29]:
predictors = np.array([1, 800, 1500])

In [30]:
predict(line, predictors)

This is probbbbbaaaabbbbllllyy the price for those variables


196773.86477386556